

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.75'
}


tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    flatDir {
        dirs 'externalmods'
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup("software.bernie.geckolib")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        url = "https://maven.blamejared.com/"
    }
    maven { url 'https://maven.blamejared.com' }
    maven {
        name "neoforgedReleases"
        url "https://maven.neoforged.net/releases"
    }
    maven {
        name = "OctoStudios"
        url = uri("https://maven.octo-studios.com/releases")
    }
    maven { url 'https://jitpack.io' }
    maven {
        name = "Iron's Maven - Release"
        url = "https://code.redspace.io/releases"
    }
    maven {
        name = "Iron's Maven - Snapshots"
        url = "https://code.redspace.io/snapshots"
    }

}


base {
    archivesName = mod_id
}

// Mojang ships Java 21 to end users starting in 1.20.5, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

// Default run configurations.
// These can be tweaked, removed, or duplicated as needed.
neoForge {
    version = "${neo_version}"
    //accessTransformers.add(file('src/main/resources/META-INF/accesstransformer.cfg'))
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = '2024.11.17'
    }
    runs {
        // applies to all the run configs below
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            systemProperty 'forge.logging.console.level', 'debug'
            sourceSet = sourceSets.main
        }

        client {
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            client()
            devLogin = true
        }

        server {
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            server()
        }


        data {
            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

    }
    mods{
        luomuksia {
            sourceSet sourceSets.main
            }
    }
        }
// Include resources generated by data generators.
sourceSets {
    main {
        resources {
            srcDirs 'src/generated/resources'
        }
    }
}
// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    //implementation "net.neoforged:neoforge:${neo_version}"

    // Example optional mod dependency with JEI
    //compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"                             // jei
    implementation "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"                              // jei

    if (minecraft_version == "1.21" || minecraft_version == "1.21.1") {                                     // ars nouveau
        implementation "com.hollingsworth.ars_nouveau:ars_nouveau-1.21.0:${ars_version}"
        // using hardcoded "1.21.0" instead of ${minecraft_version} because it's not called "1.21" which is what the minecraft_version exactly is
    } else {
        implementation "com.hollingsworth.ars_nouveau:ars_nouveau-${minecraft_version}:${ars_version}"
    }
    compileOnly "io.redspace.ironsspellbooks:irons_spellbooks:${irons_spells_version}"                                    // iron's spellbooks
    //implementation "com.github.glitchfiend:TerraBlender-neoforge:${minecraft_version}-${terrablender_version}" // terrablender


    implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"

    compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}"                                           // patchouli
    runtimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}"

    implementation "curse.maven:jade-324717:${jade_version}"                                                // waila
    implementation "curse.maven:selene-499980:${moonlight_lib_version}"                                     // moonlight lib
    implementation "top.theillusivec4.curios:curios-neoforge:${curios_version}"


    runtimeOnly "curse.maven:mmmmmmmmmmmm-225738:${literal_dummy_version}"
    compileOnly "curse.maven:tweakerge-915857:${tweakeroo_version}"
    runtimeOnly "curse.maven:tweakerge-915857:${tweakeroo_version}"
    compileOnly "curse.maven:mafglib-910766:${malilib_version}"
    runtimeOnly "curse.maven:mafglib-910766:${malilib_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
